### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by conniepintar** [338317/Aws-Manger-Bot#1]
能不能告诉一下怎么使用

**Comment by Yuzuki616** [comment]
Releases里有编译好的二进制文件，下载之后运行会生成默认配置文件，把Telegram Bot Token填进配置文件重新运行就行了。
私聊bot使用/start指令可以看到指令列表
![Screenshot_20211015-134310~2](https://user-images.githubusercontent.com/50410851/137438268-c846b148-c4b5-49af-9ff1-0b9b3208af75.png)

**Comment by ak6665607** [comment]
Log_Level: error
Bot_Token:20600***869:AAEXhJAXI5b1L****Ltil0sWGEZDelc
User_Info:
  0:
    User_Name: ""
    Now_Key: ""
    Aws_Secret: {}

大佬,我填的这样的,在WIN版里运行还是不行呢? 我的Token格式有误吗?

**Comment by Yuzuki616** [comment]
> Log_Level: error Bot_Token:20600_**869:AAEXhJAXI5b1L**_*Ltil0sWGEZDelc User_Info: 0: User_Name: "" Now_Key: "" Aws_Secret: {}
> 
> 大佬,我填的这样的,在WIN版里运行还是不行呢? 我的Token格式有误吗?

可以附上日志输出吗？

**Comment by ak6665607** [comment]
就只有EXE与config.yml这2个文件,没有其它的了.  config里面还是Log_Level: error
我是在WIN2012里面运行的EXE,跟系统有关系吗? 还是要另外开其它端口

**Comment by Yuzuki616** [comment]
> 就只有EXE与config.yml这2个文件,没有其它的了. config里面还是Log_Level: error 我是在WIN2012里面运行的EXE,跟系统有关系吗? 还是要另外开其它端口

你打开它会有控制台输出呀

**Comment by ak6665607** [comment]
啊? 我换了2台电脑,3台VPS,运行exe就直接没了..我还是以为是在后台静默运行呢.

**Comment by Yuzuki616** [comment]
> 啊? 我换了2台电脑,3台VPS,运行exe就直接没了..我还是以为是在后台静默运行呢.

你在cmd里运行看看呢，按理说应该会有控制台输出

**Comment by ak6665607** [comment]
C:\>C:\Users\mjjmjj\Downloads\Aws-Manger-Bot_windows_amd64.exe
Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Aws Manger Bot
Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Version: 1.0.0
Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot
Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Loading config...
Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Config file not found
Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Write default config file
Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Write file error: open ./config.yml: Access is denied.

提示CONFIG参数拒绝,我就是按上面的格式输入的..

**Comment by Yuzuki616** [comment]
> C:>C:\Users\mjjmjj\Downloads\Aws-Manger-Bot_windows_amd64.exe Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Aws Manger Bot Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Version: 1.0.0 Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot Aws-Manger-Bot | 10-15 17:07:10 | INFO >> Loading config... Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Config file not found Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Write default config file Aws-Manger-Bot | 10-15 17:07:10 | ERROR >> Write file error: open ./config.yml: Access is denied.
> 
> 提示CONFIG参数拒绝,我就是按上面的格式输入的..

Windows版我还没测试过，晚上我看一下。你可以先试试用管理员权限运行

**Comment by ak6665607** [comment]
应该是文件夹权限问题..我把软件的路径及下面的文件全给管理员权限看看..

**Comment by ak6665607** [comment]
文件夹权限搞定了...Token也好啦
C:\>C:\000\Aws-Manger-Bot_windows_amd64.exe
Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Aws Manger Bot
Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Version: 1.0.0
Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot
Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Loading config...
Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Done
Aws-Manger-Bot | 10-15 17:32:26 | ERROR >> Bot start error: telegram: Not Found (404)

**Comment by Yuzuki616** [comment]
> 文件夹权限搞定了...Token也好啦 C:>C:\000\Aws-Manger-Bot_windows_amd64.exe Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Aws Manger Bot Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Version: 1.0.0 Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Loading config... Aws-Manger-Bot | 10-15 17:32:25 | INFO >> Done Aws-Manger-Bot | 10-15 17:32:26 | ERROR >> Bot start error: telegram: Not Found (404)

这个应该是你的token填错了

**Comment by ak6665607** [comment]
C:\Users\wc2>1
Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Aws Manger Bot
Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Version: 1.0.0
Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot
Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Loading config...
Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Done
2021/10/16 22:36:55 runtime error: invalid memory address or nil pointer dereference
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*Bot).deferDebug
        gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:25
runtime.gopanic
        runtime/panic.go:1038
runtime.panicmem
        runtime/panic.go:221
runtime.sigpanic
        runtime/signal_windows.go:254
github.com/338317/Aws-Manger-Bot/service/tgbot.(*TgBot).setRegionKey.func1
        github.com/338317/Aws-Manger-Bot/service/tgbot/region.go:114
gopkg.in/tucnak/telebot%2ev2.(*Bot).ProcessUpdate.func8
        gopkg.in/tucnak/telebot.v2@v2.4.0/bot.go:437
gopkg.in/tucnak/telebot%2ev2.(*Bot).runHandler.func1
        gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:35
runtime.goexit
        runtime/asm_386.s:1319
---------------
查看配额,提示这个错误呀,看不到配额

**Comment by Yuzuki616** [comment]
> ## C:\Users\wc2>1
> Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Aws Manger Bot
> Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Version: 1.0.0
> Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot
> Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Loading config...
> Aws-Manger-Bot | 10-16 22:36:52 | INFO >> Done
> 2021/10/16 22:36:55 runtime error: invalid memory address or nil pointer dereference
> gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
> gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:14
> gopkg.in/tucnak/telebot%2ev2.(*Bot).deferDebug
> gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:25
> runtime.gopanic
> runtime/panic.go:1038
> runtime.panicmem
> runtime/panic.go:221
> runtime.sigpanic
> runtime/signal_windows.go:254
> github.com/338317/Aws-Manger-Bot/service/tgbot.(*TgBot).setRegionKey.func1
> github.com/338317/Aws-Manger-Bot/service/tgbot/region.go:114
> gopkg.in/tucnak/telebot%2ev2.(*Bot).ProcessUpdate.func8
> gopkg.in/tucnak/telebot.v2@v2.4.0/bot.go:437
> gopkg.in/tucnak/telebot%2ev2.(*Bot).runHandler.func1
> gopkg.in/tucnak/telebot.v2@v2.4.0/util.go:35
> runtime.goexit
> runtime/asm_386.s:1319
> 查看配额,提示这个错误呀,看不到配额

已修复，这里可以[下载最新版二进制文件](https://github.com/Yuzuki999/Aws-Manger-Bot/actions/runs/1351260576)

**Comment by ak6665607** [comment]
大佬,你的BOT我很喜欢 ,目前发现AWS风控严重,如果在同一台服务器运行BOT, 连续CLI几个AWS号,后面的就会风控..请问能否加入代理IP功能?比如: 在config.yml里填入代理HTTP的信息,然后让BOT使用代理去处理数据..

**Comment by Yuzuki616** [comment]
> 大佬,你的BOT我很喜欢 ,目前发现AWS风控严重,如果在同一台服务器运行BOT, 连续CLI几个AWS号,后面的就会风控..请问能否加入代理IP功能?比如: 在config.yml里填入代理HTTP的信息,然后让BOT使用代理去处理数据..

可以添加HTTP_PROXY环境变量实现代理，之后可能会加个给每个密钥添加不同的代理的功能

**Comment by ak6665607** [comment]
> 之后

期待哦..用简单的方式 实现强大的功能..很棒

**Comment by Yuzuki616** [comment]
> > 之后
> 
> 期待哦..用简单的方式 实现强大的功能..很棒

加上了
