### ISSUE TITLE
创建ec2时提示输入硬盘大小该怎么填？

### ISSUE THREAD

**Issue by yanyanlongxia** [338317/Aws-Manger-Bot#2]
创建ec2时提示输入硬盘大小该怎么填？
输入8 或 8G 好像都没有反应

**Comment by Yuzuki616** [comment]
直接输数字就行，看下日志有没有报错

**Comment by yanyanlongxia** [comment]
输入8之后bot没反应。也没有报错，只有这些：
Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Aws Manger Bot 
Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Version: 1.0.2 
Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot 
Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Loading config... 
Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Done

**Comment by Yuzuki616** [comment]
> 输入8之后bot没反应。也没有报错，只有这些： Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Aws Manger Bot Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Version: 1.0.2 Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Github: https://github.com/yuzuki999/Aws-Manger-Bot Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Loading config... Aws-Manger-Bot | 10-31 19:54:36 | INFO >> Done

我这边试着没问题，重新运行看看呢
